// src/components/WelcomeScreen/Splash.jsx
import { faClock } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useEffect, useRef, useState } from "react";

const Splash = () => {
  const [displaySplash, setDisplaySplash] = useState(true);
  const splashRef = useRef();

  useEffect(() => {
    setTimeout(() => {
      splashRef.current.style.opacity = "0";
      setDisplaySplash(false);
    }, 2000);
  }, []);

  if (displaySplash) {
    return (
      <section ref={splashRef} className="fixed transition-all opacity-100 flex-wrap flex flex-col items-center z-20 top-0 left-0 right-0 bottom-0 bg-violet-bg">
        <h2 className="relative top-36 text-center text-6xl font-[poppins] text-violet-lighter font-bold">POMODORO TIMER</h2>
        <i className="text-violet-lighter relative top-36 mt-10 text-5xl">
          <FontAwesomeIcon icon={faClock} />
        </i>
      </section>
    );
  }
};

export default Splash;

// src/app/UI/Splash.svelte
<script lang="ts">
  import { store } from "../store";
  import background from "$lib/images/splash_background.jpg";
  import Icon from "@iconify/svelte";
  $: primary = $store.theme.primary;
  $: secondary = $store.theme.secondary;
  $: cto = $store.theme.cto;
</script>

<section style="background-color: {secondary}; " class="fixed w-[100vw] h-[100vh] z-50">
  <div class="flex flex-col items-center justify-center relative top-60">
    <p style="color: black" class="text-4xl font-semibold relative}">Pomodoro <span class="font-bold">PRO</span></p>
    <Icon style='color: black' class="text-7xl" icon="icon-park-outline:tomato" />
  </div>
</section>

<style>
  section::before {
    content: "";
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    opacity: 0.8;
    /* z-index: -1; */

  }
</style>
